version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: frontend
    image: frontend_image
    environment:
      NODE_ENV: production
    ports:
      - "5030:80" 
    volumes:
      - .:/app